<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="6" passed="3" failed="3" skipped="0">
  <reporter-output>
  </reporter-output>
  <suite started-at="2022-12-16T18:44:49 IST" name="Default Suite" finished-at="2022-12-16T18:48:05 IST" duration-ms="195951">
    <groups>
    </groups>
    <test started-at="2022-12-16T18:44:49 IST" name="Command line test b3445efa-5098-4ef4-a6be-2280c14f3dbd" finished-at="2022-12-16T18:45:24 IST" duration-ms="35164">
      <class name="Test.TestUserDelete">
        <test-method is-config="true" signature="before_Class()[pri:0, instance:Test.TestUserDelete@60957c0f]" started-at="2022-12-16T18:44:49 IST" name="before_Class" finished-at="2022-12-16T18:45:03 IST" duration-ms="13874" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="deleteUserfromList()[pri:0, instance:Test.TestUserDelete@60957c0f]" started-at="2022-12-16T18:45:03 IST" name="deleteUserfromList" finished-at="2022-12-16T18:45:19 IST" duration-ms="16029" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate the element]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate the element
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.element(webAction.java:341)
at Pages.UserCreationandUserDelete.searchforUser(UserCreationandUserDelete.java:86)
at Pages.UserCreationandUserDelete.validateUserCreation(UserCreationandUserDelete.java:96)
at Test.TestUserDelete.deleteUserfromList(TestUserDelete.java:30)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- deleteUserfromList -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Test.TestUserDelete@60957c0f]" started-at="2022-12-16T18:45:19 IST" name="getResult" finished-at="2022-12-16T18:45:22 IST" duration-ms="3053" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=deleteUserfromList status=FAILURE method=TestUserDelete.deleteUserfromList()[pri:0, instance:Test.TestUserDelete@60957c0f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.TestUserDelete@60957c0f]" started-at="2022-12-16T18:45:22 IST" name="logoutFromApplication" finished-at="2022-12-16T18:45:24 IST" duration-ms="2148" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.TestUserDelete -->
    </test> <!-- Command line test b3445efa-5098-4ef4-a6be-2280c14f3dbd -->
    <test started-at="2022-12-16T18:45:24 IST" name="Command line test c73a35f6-c75a-4516-8c8c-b73532ba2adb" finished-at="2022-12-16T18:45:57 IST" duration-ms="33223">
      <class name="Test.LoginTest">
        <test-method is-config="true" signature="before_Class()[pri:0, instance:Test.LoginTest@3ecd267f]" started-at="2022-12-16T18:45:24 IST" name="before_Class" finished-at="2022-12-16T18:45:36 IST" duration-ms="12164" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="loginTest()[pri:0, instance:Test.LoginTest@3ecd267f]" started-at="2022-12-16T18:45:36 IST" name="loginTest" finished-at="2022-12-16T18:45:55 IST" duration-ms="18711" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Test.LoginTest@3ecd267f]" started-at="2022-12-16T18:45:55 IST" name="getResult" finished-at="2022-12-16T18:45:55 IST" duration-ms="238" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=loginTest status=SUCCESS method=LoginTest.loginTest()[pri:0, instance:Test.LoginTest@3ecd267f] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.LoginTest@3ecd267f]" started-at="2022-12-16T18:45:55 IST" name="logoutFromApplication" finished-at="2022-12-16T18:45:57 IST" duration-ms="2107" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.LoginTest -->
    </test> <!-- Command line test c73a35f6-c75a-4516-8c8c-b73532ba2adb -->
    <test started-at="2022-12-16T18:45:57 IST" name="Command line test 06e5ab06-bcad-4e30-90e5-e6f70b2f78cc" finished-at="2022-12-16T18:46:55 IST" duration-ms="57761">
      <class name="Test.TestUserCreation">
        <test-method is-config="true" signature="before_Class()[pri:0, instance:Test.TestUserCreation@319bc845]" started-at="2022-12-16T18:45:57 IST" name="before_Class" finished-at="2022-12-16T18:46:06 IST" duration-ms="8502" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="userCreation()[pri:0, instance:Test.TestUserCreation@319bc845]" started-at="2022-12-16T18:46:06 IST" name="userCreation" finished-at="2022-12-16T18:46:52 IST" duration-ms="46435" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Test.TestUserCreation@319bc845]" started-at="2022-12-16T18:46:52 IST" name="getResult" finished-at="2022-12-16T18:46:53 IST" duration-ms="761" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=userCreation status=SUCCESS method=TestUserCreation.userCreation()[pri:0, instance:Test.TestUserCreation@319bc845] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.TestUserCreation@319bc845]" started-at="2022-12-16T18:46:53 IST" name="logoutFromApplication" finished-at="2022-12-16T18:46:55 IST" duration-ms="2060" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.TestUserCreation -->
    </test> <!-- Command line test 06e5ab06-bcad-4e30-90e5-e6f70b2f78cc -->
    <test started-at="2022-12-16T18:46:55 IST" name="Command line test 5ff9e8e9-a323-4c69-b5ba-24c2d111e055" finished-at="2022-12-16T18:47:25 IST" duration-ms="30126">
      <class name="Test.leaveTest">
        <test-method is-config="true" signature="before_Class()[pri:0, instance:Test.leaveTest@20b12f8a]" started-at="2022-12-16T18:46:55 IST" name="before_Class" finished-at="2022-12-16T18:47:03 IST" duration-ms="8079" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="applyleave()[pri:0, instance:Test.leaveTest@20b12f8a]" started-at="2022-12-16T18:47:03 IST" name="applyleave" finished-at="2022-12-16T18:47:22 IST" duration-ms="18940" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate the element]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate the element
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.element(webAction.java:341)
at Pages.leavepagee.applyLeave(leavepagee.java:58)
at Test.leaveTest.applyleave(leaveTest.java:22)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- applyleave -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Test.leaveTest@20b12f8a]" started-at="2022-12-16T18:47:22 IST" name="getResult" finished-at="2022-12-16T18:47:23 IST" duration-ms="1059" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=applyleave status=FAILURE method=leaveTest.applyleave()[pri:0, instance:Test.leaveTest@20b12f8a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.leaveTest@20b12f8a]" started-at="2022-12-16T18:47:23 IST" name="logoutFromApplication" finished-at="2022-12-16T18:47:25 IST" duration-ms="2046" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.leaveTest -->
    </test> <!-- Command line test 5ff9e8e9-a323-4c69-b5ba-24c2d111e055 -->
    <test started-at="2022-12-16T18:47:25 IST" name="Command line test 8fcd2c12-af84-4650-bc53-8b3487b8e32e" finished-at="2022-12-16T18:47:42 IST" duration-ms="16759">
      <class name="Test.EmployeeDownloadTest$TestUserCreation">
        <test-method is-config="true" signature="before_Class()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5e01a982]" started-at="2022-12-16T18:47:25 IST" name="before_Class" finished-at="2022-12-16T18:47:32 IST" duration-ms="7470" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="userCreation()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5e01a982]" started-at="2022-12-16T18:47:32 IST" name="userCreation" finished-at="2022-12-16T18:47:39 IST" duration-ms="6607" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- userCreation -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5e01a982]" started-at="2022-12-16T18:47:39 IST" name="getResult" finished-at="2022-12-16T18:47:40 IST" duration-ms="633" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=userCreation status=SUCCESS method=EmployeeDownloadTest$TestUserCreation.userCreation()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5e01a982] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.EmployeeDownloadTest$TestUserCreation@5e01a982]" started-at="2022-12-16T18:47:40 IST" name="logoutFromApplication" finished-at="2022-12-16T18:47:42 IST" duration-ms="2047" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
      </class> <!-- Test.EmployeeDownloadTest$TestUserCreation -->
    </test> <!-- Command line test 8fcd2c12-af84-4650-bc53-8b3487b8e32e -->
    <test started-at="2022-12-16T18:47:42 IST" name="Command line test 45c9945a-6a91-4467-b737-767b9b3e55fb" finished-at="2022-12-16T18:48:05 IST" duration-ms="22815">
      <class name="Test.calenderTest">
        <test-method is-config="true" signature="before_suite()[pri:0, instance:Test.calenderTest@37ddb69a]" started-at="2022-12-16T18:44:48 IST" name="before_suite" finished-at="2022-12-16T18:44:49 IST" duration-ms="552" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_suite -->
        <test-method is-config="true" signature="before_Class()[pri:0, instance:Test.calenderTest@37ddb69a]" started-at="2022-12-16T18:47:42 IST" name="before_Class" finished-at="2022-12-16T18:47:48 IST" duration-ms="6549" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- before_Class -->
        <test-method signature="calender_test()[pri:0, instance:Test.calenderTest@37ddb69a]" started-at="2022-12-16T18:47:48 IST" name="calender_test" finished-at="2022-12-16T18:48:01 IST" duration-ms="13146" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to locate the element]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to locate the element
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.element(webAction.java:341)
at Pages.CalenderHandling.calender(CalenderHandling.java:24)
at Test.calenderTest.calender_test(calenderTest.java:18)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:173)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:824)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:146)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- calender_test -->
        <test-method is-config="true" signature="getResult(org.testng.ITestResult)[pri:0, instance:Test.calenderTest@37ddb69a]" started-at="2022-12-16T18:48:01 IST" name="getResult" finished-at="2022-12-16T18:48:03 IST" duration-ms="1063" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=calender_test status=FAILURE method=calenderTest.calender_test()[pri:0, instance:Test.calenderTest@37ddb69a] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- getResult -->
        <test-method is-config="true" signature="logoutFromApplication()[pri:0, instance:Test.calenderTest@37ddb69a]" started-at="2022-12-16T18:48:03 IST" name="logoutFromApplication" finished-at="2022-12-16T18:48:05 IST" duration-ms="2053" status="FAIL">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Unable to logout from the application]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Unable to logout from the application
at org.testng.Assert.fail(Assert.java:99)
at Pages.webAction.logoutFromApplication(webAction.java:166)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:568)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:133)
at org.testng.internal.MethodInvocationHelper.invokeMethodConsideringTimeout(MethodInvocationHelper.java:62)
at org.testng.internal.ConfigInvoker.invokeConfigurationMethod(ConfigInvoker.java:385)
at org.testng.internal.ConfigInvoker.invokeConfigurations(ConfigInvoker.java:321)
at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:130)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
at org.testng.TestRunner.privateRun(TestRunner.java:794)
at org.testng.TestRunner.run(TestRunner.java:596)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:377)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:371)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:332)
at org.testng.SuiteRunner.run(SuiteRunner.java:276)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1212)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1134)
at org.testng.TestNG.runSuites(TestNG.java:1063)
at org.testng.TestNG.run(TestNG.java:1031)
at Test.TestNGXML.xml(TestNGXML.java:121)
at Test.TestNGXML.main(TestNGXML.java:126)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logoutFromApplication -->
        <test-method is-config="true" signature="closeDriver()[pri:0, instance:Test.calenderTest@37ddb69a]" started-at="2022-12-16T18:48:05 IST" name="closeDriver" finished-at="2022-12-16T18:48:05 IST" duration-ms="64" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeDriver -->
      </class> <!-- Test.calenderTest -->
    </test> <!-- Command line test 45c9945a-6a91-4467-b737-767b9b3e55fb -->
  </suite> <!-- Default Suite -->
</testng-results>
